### ISSUE TITLE
Simulation about the narrowband signal sources

### ISSUE THREAD

**Issue by YetiXie1994** [msamsami/doa-estimation-music#1]
PPT in page 4 says that all frequencies are different.
Why in matlab, difference narrowband signal sources have the same frequency?
If the frequency is the same, then the sources are dependent of one another

**Comment by msamsami** [comment]
The MATLAB code is written based on the project guideline ("MUSIC Algorithm Project.pdf"), on the first page of which is stated that: "It is assumed that the frequency of all sources is 10^6 Hz".
